"""Captcha-Updated

迁移 ID: afb5fc69c91d
父迁移: 33e081945e54
创建时间: 2025-07-03 20:19:42.739769

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "afb5fc69c91d"
down_revision: str | Sequence[str] | None = "33e081945e54"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_config", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("captcha_timeout", sa.BigInteger(), nullable=False)
        )
        batch_op.add_column(sa.Column("captcha_format", sa.Text(), nullable=False))
        batch_op.add_column(
            sa.Column("captcha_length", sa.BigInteger(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_config", schema=None) as batch_op:
        batch_op.drop_column("captcha_length")
        batch_op.drop_column("captcha_format")
        batch_op.drop_column("captcha_timeout")

    # ### end Alembic commands ###
