"""创建SubAdmin表

迁移 ID: bfe784d0886d
父迁移: f65219e033c6
创建时间: 2025-07-08 22:20:16.802765

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

revision: str = "bfe784d0886d"
down_revision: str | Sequence[str] | None = "f65219e033c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sub_admin",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sub_admin")),
        info={"bind_key": ""},
    )
    with op.batch_alter_table("sub_admin", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sub_admin_group_id"), ["group_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sub_admin_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("group_config", schema=None) as batch_op:
        batch_op.alter_column(
            "captcha_format",
            existing_type=sa.TEXT(),
            type_=sa.BigInteger(),
            existing_nullable=False,
        )
        batch_op.drop_column("sub_admins")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_config", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "sub_admins",
                sqlite.JSON(),
                server_default=sa.text("'[]'"),
                nullable=False,
            )
        )
        batch_op.alter_column(
            "captcha_format",
            existing_type=sa.BigInteger(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )

    with op.batch_alter_table("sub_admin", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sub_admin_user_id"))
        batch_op.drop_index(batch_op.f("ix_sub_admin_group_id"))

    op.drop_table("sub_admin")
    # ### end Alembic commands ###
