"""添加bw

迁移 ID: c1c52311f8be
父迁移: bfe784d0886d
创建时间: 2025-09-30 17:43:27.596090

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

revision: str = "c1c52311f8be"
down_revision: str | Sequence[str] | None = "bfe784d0886d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_config", schema=None) as batch_op:
        batch_op.add_column(sa.Column("badwords_check", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("custom_badwords", sa.JSON(), nullable=True))
        batch_op.add_column(
            sa.Column("badwords_check_mode", sa.String(length=20), nullable=False)
        )
        batch_op.drop_column("anti_spam")
        batch_op.drop_column("nailong")
        batch_op.drop_column("judge")
        batch_op.drop_column("anti_recall")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_config", schema=None) as batch_op:
        batch_op.add_column(sa.Column("anti_recall", sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column("judge", sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column("nailong", sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column("anti_spam", sqlite.JSON(), nullable=False))
        batch_op.drop_column("badwords_check_mode")
        batch_op.drop_column("custom_badwords")
        batch_op.drop_column("badwords_check")

    # ### end Alembic commands ###
